#!/usr/bin/env python3
"""Materialize fetched corpus instances at their pinned SHAs.

Stdlib-only (urllib). For each manifest row with ``source == "fetched"`` this
downloads the listed upstream paths verbatim from
``raw.githubusercontent.com/<repo>/<sha>/<path>`` into
``corpus/_fetched/<instance_id>/<path>`` and stamps the directory with a
``.fetched.json`` receipt. Fetched content is never executed, imported, or
installed; it is written to disk as data only.

Usage:
    python3 scripts/fetch_corpus.py            # materialize all fetched instances
    python3 scripts/fetch_corpus.py --only ***REMOVED***
    python3 scripts/fetch_corpus.py --check    # verify SHAs + materialization, no downloads
    python3 scripts/fetch_corpus.py --emit-expected   # regenerate corpus/EXPECTEDRESULTS.csv

corpus/EXPECTEDRESULTS.csv is generated by this script (--emit-expected and
implicitly after a successful fetch); it is never hand-edited.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CORPUS = REPO_ROOT / "corpus"
MANIFEST = CORPUS / "manifest.jsonl"
FETCHED_ROOT = CORPUS / "_fetched"
EXPECTED_CSV = CORPUS / "EXPECTEDRESULTS.csv"

RAW_URL = "https://raw.githubusercontent.com/{repo}/{sha}/{path}"
USER_AGENT = "mcp-ssrf-audit-corpus-fetcher/1.0"
TIMEOUT = 30


def load_manifest() -> list[dict]:
    rows = []
    with MANIFEST.open() as f:
        for i, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as e:
                sys.exit(f"manifest.jsonl line {i}: invalid JSON: {e}")
    return rows


def sha_resolves(repo: str, sha: str, probe_path: str) -> bool:
    """Verify the pinned SHA resolves upstream without fetching full trees.

    A HEAD request against the raw content URL doubles as the existence
    proof: content addressed by <repo>/<sha>/<path> can only serve if that
    commit and path are real, so a 200 means the pinned checkout resolves.
    """
    url = RAW_URL.format(repo=repo, sha=sha, path=urllib.request.quote(probe_path))
    req = urllib.request.Request(
        url, method="HEAD", headers={"User-Agent": USER_AGENT}
    )
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            return resp.status == 200
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return False
        if e.code in (403, 429):
            return None  # rate-limited: unverified, not proven missing
        raise


def download_file(repo: str, sha: str, path: str, dest: Path) -> None:
    url = RAW_URL.format(repo=repo, sha=sha, path=urllib.request.quote(path))
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
        body = resp.read()
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(body)


def materialize(row: dict) -> tuple[int, str]:
    """Fetch one instance's files. Returns (file_count, dest_dir)."""
    instance_id = row["instance_id"]
    dest_dir = FETCHED_ROOT / instance_id
    count = 0
    for path in row["paths"]:
        dest = dest_dir / path
        download_file(row["repo"], row["sha"], path, dest)
        count += 1
    receipt = {
        "instance_id": instance_id,
        "repo": row["repo"],
        "sha": row["sha"],
        "fetched_with": "scripts/fetch_corpus.py",
        "sample_ids": [row["sample_id"]],
        "license_spdx": row["license_spdx"],
    }
    receipt_path = dest_dir / ".fetched.json"
    if receipt_path.exists():
        try:
            prior = json.loads(receipt_path.read_text())
            receipt["sample_ids"] = sorted(
                set(prior.get("sample_ids", [])) | set(receipt["sample_ids"])
            )
        except json.JSONDecodeError:
            pass
    receipt_path.write_text(json.dumps(receipt, indent=2) + "\n")
    return count, str(dest_dir.relative_to(REPO_ROOT))


def is_materialized(row: dict) -> bool:
    if row["source"] == "vendored":
        return all((REPO_ROOT / p).is_file() for p in row.get("corpus_paths", []))
    dest = FETCHED_ROOT / row["instance_id"]
    return all((dest / p).is_file() for p in row["paths"])


def emit_expected(rows: list[dict]) -> None:
    """Regenerate EXPECTEDRESULTS.csv: one row per labeled corpus file."""
    with EXPECTED_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(
            [
                "sample_id",
                "instance_id",
                "repo",
                "sha",
                "file",
                "language",
                "expected",
                "tier",
                "source",
                "materialized",
            ]
        )
        for row in rows:
            materialized = "yes" if is_materialized(row) else "no"
            expected = ";".join(row["expected"])
            if row["source"] == "fetched":
                files = [
                    str(Path("corpus") / "_fetched" / row["instance_id"] / p)
                    for p in row["paths"]
                ]
            else:
                files = row.get("corpus_paths", [])
            for file in files:
                w.writerow(
                    [
                        row["sample_id"],
                        row["instance_id"],
                        row["repo"],
                        row["sha"],
                        file,
                        row["language"],
                        expected,
                        row["tier"],
                        row["source"],
                        materialized,
                    ]
                )


def cmd_check(rows: list[dict]) -> int:
    """Verify pinned SHAs resolve upstream; report materialization state."""
    seen: set[tuple[str, str]] = set()
    bad = 0
    for row in rows:
        key = (row["repo"], row["sha"])
        if key in seen:
            continue
        seen.add(key)
        ok = sha_resolves(row["repo"], row["sha"], row["paths"][0])
        status = {True: "OK", False: "MISSING", None: "UNVERIFIED"}[ok]
        print(f"{status:10s} {row['repo']}@{row['sha'][:12]} ({row['sample_id']})")
        if ok is False:
            bad += 1
    print()
    for row in rows:
        state = "materialized" if is_materialized(row) else "unmaterialized"
        print(f"{state:15s} {row['sample_id']} [{row['source']}, {row['tier']}]")
    if bad:
        print(f"\n{bad} pinned SHA(s) did not resolve upstream")
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--only", metavar="ID",
                    help="materialize only the instance whose id or sample_id matches")
    ap.add_argument("--check", action="store_true",
                    help="verify pinned SHAs resolve and report materialization state")
    ap.add_argument("--emit-expected", action="store_true",
                    help="regenerate corpus/EXPECTEDRESULTS.csv and exit")
    args = ap.parse_args()

    rows = load_manifest()

    if args.emit_expected:
        emit_expected(rows)
        print(f"wrote {EXPECTED_CSV.relative_to(REPO_ROOT)}")
        return 0

    if args.check:
        return cmd_check(rows)

    fetched = [r for r in rows if r["source"] == "fetched"]
    if args.only:
        fetched = [
            r for r in fetched
            if r["instance_id"] == args.only or r["sample_id"] == args.only
        ]
        if not fetched:
            sys.exit(f"no fetched manifest row matches --only {args.only!r}")

    failures = 0
    done: set[str] = set()
    for row in fetched:
        iid = row["instance_id"]
        if iid in done:
            continue
        try:
            if sha_resolves(row["repo"], row["sha"], row["paths"][0]) is False:
                print(f"FAIL {iid}: sha {row['sha'][:12]} does not resolve on {row['repo']}")
                failures += 1
                continue
            n, dest = materialize(row)
            done.add(iid)
            print(f"ok   {iid}: {n} file(s) -> {dest}")
        except (urllib.error.URLError, OSError) as e:
            print(f"FAIL {iid}: {e}")
            failures += 1

    emit_expected(rows)
    if failures:
        return 1
    print("all fetched instances materialized")
    return 0


if __name__ == "__main__":
    sys.exit(main())
