#!/usr/bin/env python3
"""Materialize fetched corpus instances at their pinned SHAs.

Stdlib-only (urllib). For each manifest row with ``source == "fetched"`` this
downloads the listed upstream paths verbatim from
``raw.githubusercontent.com/<repo>/<sha>/<path>`` into
``corpus/_fetched/<instance_id>/<path>`` and stamps the directory with a
``.fetched.json`` receipt. Fetched content is never executed, imported, or
installed; it is written to disk as data only.

Usage:
    python3 scripts/fetch_corpus.py            # materialize all fetched instances
    python3 scripts/fetch_corpus.py --only g4-g8-kazuph-mcp-fetch-head
    python3 scripts/fetch_corpus.py --check    # verify SHAs + materialization, no downloads
    python3 scripts/fetch_corpus.py --emit-expected   # regenerate corpus/EXPECTEDRESULTS.csv

corpus/EXPECTEDRESULTS.csv is generated by this script (--emit-expected and
implicitly after a successful fetch); it is never hand-edited.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path, PurePosixPath

REPO_ROOT = Path(__file__).resolve().parent.parent
CORPUS = REPO_ROOT / "corpus"
MANIFEST = CORPUS / "manifest.jsonl"
FETCHED_ROOT = CORPUS / "_fetched"
EXPECTED_CSV = CORPUS / "EXPECTEDRESULTS.csv"

RAW_URL = "https://raw.githubusercontent.com/{repo}/{sha}/{path}"
USER_AGENT = "mcp-ssrf-audit-corpus-fetcher/1.0"
TIMEOUT = 30
# A corpus sample is source code; anything past this is not a file we
# vendored on purpose.
MAX_FILE_BYTES = 2 * 1024 * 1024

SHA_RE = re.compile(r"^[0-9a-f]{40}$")
REPO_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
# instance_id doubles as a directory name under corpus/_fetched.
INSTANCE_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    """Refuse redirects.

    The pin guarantee (content addressed by <repo>/<sha>/<path>) only
    holds while the request stays on raw.githubusercontent.com; a
    redirect would serve bytes the manifest did not pin.
    """

    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


_OPENER = urllib.request.build_opener(_NoRedirect)


def _fail(msg: str) -> "SystemExit":
    return SystemExit(f"fetch_corpus: {msg}")


def validate_row(row: dict, line: int) -> None:
    """Reject manifest rows that could fetch or write outside the pin.

    Raises SystemExit (the script's error channel) on the first problem.
    """
    where = f"manifest.jsonl line {line} ({row.get('sample_id', '?')})"
    sha = row.get("sha", "")
    if not SHA_RE.match(str(sha)):
        raise _fail(
            f"{where}: sha must be a full 40-char commit hex, got {sha!r}"
        )
    repo = row.get("repo", "")
    if not REPO_RE.match(str(repo)):
        raise _fail(
            f"{where}: repo must be 'owner/name', got {repo!r}"
        )
    iid = row.get("instance_id", "")
    if not INSTANCE_ID_RE.match(str(iid)) or ".." in str(iid):
        raise _fail(
            f"{where}: instance_id must be a single safe directory "
            f"name, got {iid!r}"
        )
    paths = row.get("paths")
    if not isinstance(paths, list) or not paths:
        raise _fail(f"{where}: paths must be a nonempty list")
    for p in paths:
        pure = PurePosixPath(str(p))
        if not isinstance(p, str) or pure.is_absolute() or ".." in pure.parts:
            raise _fail(
                f"{where}: paths entries must be relative paths "
                f"without '..' segments, got {p!r}"
            )
    dest = (FETCHED_ROOT / iid).resolve()
    if FETCHED_ROOT.resolve() not in dest.parents:
        raise _fail(f"{where}: instance_id escapes corpus/_fetched")


def load_manifest() -> list[tuple[int, dict]]:
    rows = []
    with MANIFEST.open() as f:
        for i, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as e:
                raise _fail(f"manifest.jsonl line {i}: invalid JSON: {e}")
            validate_row(row, i)
            rows.append((i, row))
    return rows


def sha_resolves(repo: str, sha: str, probe_path: str) -> bool | None:
    """Verify the pinned SHA resolves upstream without fetching full trees.

    A HEAD request against the raw content URL doubles as the existence
    proof: content addressed by <repo>/<sha>/<path> can only serve if that
    commit and path are real, so a 200 means the pinned checkout resolves.
    """
    url = RAW_URL.format(repo=repo, sha=sha, path=urllib.request.quote(probe_path))
    req = urllib.request.Request(
        url, method="HEAD", headers={"User-Agent": USER_AGENT}
    )
    try:
        with _OPENER.open(req, timeout=TIMEOUT) as resp:
            return resp.status == 200
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return False
        if e.code in (403, 429):
            return None  # rate-limited: unverified, not proven missing
        raise


def _write_atomic(dest: Path, body: bytes) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=dest.parent, prefix=".fetch-")
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(body)
        os.replace(tmp, dest)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def download_file(repo: str, sha: str, path: str, dest: Path) -> None:
    url = RAW_URL.format(repo=repo, sha=sha, path=urllib.request.quote(path))
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with _OPENER.open(req, timeout=TIMEOUT) as resp:
        body = resp.read(MAX_FILE_BYTES + 1)
    if len(body) > MAX_FILE_BYTES:
        raise OSError(
            f"{path}: upstream file exceeds {MAX_FILE_BYTES} bytes"
        )
    _write_atomic(dest, body)


def materialize(rows: list[dict]) -> tuple[int, str]:
    """Fetch one instance's files. Returns (file_count, dest_dir).

    ``rows`` are all manifest rows sharing one instance_id; their path
    lists are unioned so two sample rows pointing at the same instance
    cannot silently drop each other's files.
    """
    instance_id = rows[0]["instance_id"]
    dest_dir = FETCHED_ROOT / instance_id
    paths = sorted({p for row in rows for p in row["paths"]})
    for path in paths:
        download_file(rows[0]["repo"], rows[0]["sha"], path, dest_dir / path)
    receipt = {
        "instance_id": instance_id,
        "repo": rows[0]["repo"],
        "sha": rows[0]["sha"],
        "fetched_with": "scripts/fetch_corpus.py",
        "sample_ids": sorted({row["sample_id"] for row in rows}),
        "license_spdx": rows[0].get("license_spdx"),
    }
    receipt_path = dest_dir / ".fetched.json"
    if receipt_path.exists():
        try:
            prior = json.loads(receipt_path.read_text())
            receipt["sample_ids"] = sorted(
                set(prior.get("sample_ids", [])) | set(receipt["sample_ids"])
            )
        except json.JSONDecodeError:
            pass
    _write_atomic(
        receipt_path, (json.dumps(receipt, indent=2) + "\n").encode()
    )
    return len(paths), str(dest_dir.relative_to(REPO_ROOT))


def is_materialized(row: dict) -> bool:
    if row["source"] == "vendored":
        return all(
            (REPO_ROOT / p).is_file() for p in row.get("corpus_paths", [])
        )
    dest = FETCHED_ROOT / row["instance_id"]
    return all((dest / p).is_file() for p in row["paths"])


def emit_expected(rows: list[dict]) -> None:
    """Regenerate EXPECTEDRESULTS.csv: one row per labeled corpus file."""
    fd, tmp = tempfile.mkstemp(
        dir=EXPECTED_CSV.parent, prefix=".expected-", suffix=".csv"
    )
    try:
        with os.fdopen(fd, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(
                [
                    "sample_id",
                    "instance_id",
                    "repo",
                    "sha",
                    "file",
                    "language",
                    "expected",
                    "tier",
                    "source",
                    "materialized",
                ]
            )
            for row in rows:
                materialized = "yes" if is_materialized(row) else "no"
                expected = ";".join(row["expected"])
                if row["source"] == "fetched":
                    files = [
                        str(
                            Path("corpus")
                            / "_fetched"
                            / row["instance_id"]
                            / p
                        )
                        for p in row["paths"]
                    ]
                else:
                    files = row.get("corpus_paths", [])
                for file in files:
                    w.writerow(
                        [
                            row["sample_id"],
                            row["instance_id"],
                            row["repo"],
                            row["sha"],
                            file,
                            row["language"],
                            expected,
                            row["tier"],
                            row["source"],
                            materialized,
                        ]
                    )
        os.replace(tmp, EXPECTED_CSV)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def cmd_check(rows: list[dict]) -> int:
    """Verify pinned SHAs resolve upstream; report materialization state."""
    seen: set[tuple[str, str]] = set()
    bad = 0
    unverified = 0
    for row in rows:
        key = (row["repo"], row["sha"])
        if key in seen:
            continue
        seen.add(key)
        detail = ""
        try:
            ok = sha_resolves(row["repo"], row["sha"], row["paths"][0])
        except (urllib.error.URLError, OSError) as e:
            ok = None
            detail = f" [{e}]"
        status = {True: "OK", False: "MISSING", None: "UNVERIFIED"}[ok]
        print(
            f"{status:10s} {row['repo']}@{row['sha'][:12]} "
            f"({row['sample_id']}){detail}"
        )
        if ok is False:
            bad += 1
        elif ok is None:
            unverified += 1
    print()
    for row in rows:
        state = "materialized" if is_materialized(row) else "unmaterialized"
        print(f"{state:15s} {row['sample_id']} [{row['source']}, {row['tier']}]")
    if bad:
        print(f"\n{bad} pinned SHA(s) did not resolve upstream")
    if unverified:
        print(
            f"{unverified} pinned SHA(s) could not be verified "
            "(rate-limited or upstream error)"
        )
    # A check that verified nothing must not exit green.
    if bad or unverified or not seen:
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--only", metavar="ID",
                    help="materialize only the instance whose id or sample_id matches")
    ap.add_argument("--check", action="store_true",
                    help="verify pinned SHAs resolve and report materialization state")
    ap.add_argument("--emit-expected", action="store_true",
                    help="regenerate corpus/EXPECTEDRESULTS.csv and exit")
    args = ap.parse_args()

    rows = [row for _line, row in load_manifest()]

    if args.emit_expected:
        emit_expected(rows)
        print(f"wrote {EXPECTED_CSV.relative_to(REPO_ROOT)}")
        return 0

    if args.check:
        return cmd_check(rows)

    fetched = [r for r in rows if r["source"] == "fetched"]
    if args.only:
        fetched = [
            r for r in fetched
            if r["instance_id"] == args.only or r["sample_id"] == args.only
        ]
        if not fetched:
            sys.exit(f"no fetched manifest row matches --only {args.only!r}")

    # Group by instance_id so every row's paths materialize even when
    # two samples share one upstream instance.
    by_instance: dict[str, list[dict]] = {}
    for row in fetched:
        by_instance.setdefault(row["instance_id"], []).append(row)

    failures = 0
    for iid, group in sorted(by_instance.items()):
        try:
            if sha_resolves(
                group[0]["repo"], group[0]["sha"], group[0]["paths"][0]
            ) is False:
                print(
                    f"FAIL {iid}: sha {group[0]['sha'][:12]} does not "
                    f"resolve on {group[0]['repo']}"
                )
                failures += 1
                continue
            n, dest = materialize(group)
            print(f"ok   {iid}: {n} file(s) -> {dest}")
        except (urllib.error.URLError, OSError) as e:
            print(f"FAIL {iid}: {e}")
            failures += 1

    emit_expected(rows)
    if failures:
        return 1
    print("all fetched instances materialized")
    return 0


if __name__ == "__main__":
    sys.exit(main())
